### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by Lucstay11** [90N45-d3v/90N45-d3v.github.io#1]
The project is styler but you could have added a server return (with php for example) to have a real command return!

**Comment by 90N45-d3v** [comment]
Like a PHP-Shell using [exec()](https://www.php.net/manual/en/function.exec.php)?
I don‘t think this is clever… I mean it‘s like having SSH access open for every visitor by design.

In addition, I would have had to implement my custom command results as well. Just like using JS, but slower because it has to send/receive more data over the WAN.

Of course, I could use a server-side language to implement the command requests like SSH/Telnet. But I did it this way. It works and even has its advantages when it comes to performance, since the processing of the commands is only done by the client.

I think I understand what you mean and like the approach, but I've now done it with JavaScript, it just wouldn't make sense to rebuild everything just to make the structure similar to SSH/Telnet

**Comment by Lucstay11** [comment]
Yes of course, but in a global case your project is installed locally and the user has the choice or not to put it on a public port. Its use could be to want to communicate with its Kali terminal for example via a web interface if no terminal is available, hence the interest of a real feedback! Something like this is my latest project, try it https://github.com/Lucstay11/Chat-bot-GPT-Bash

**Comment by 90N45-d3v** [comment]
Your project looks great!
Are Chat GPT and the shell in the same chat? If so, it's definitely a cool thing... interesting to combine both features.

But it's just not the point for my project here. The website is not a terminal to control computers remotely, but serves as a normal website about me and my stuff... just in a special terminal style.

If I have time, I'd be happy to take a look at your Bot and give you feedback.

**Comment by Lucstay11** [comment]
Yes, everything is in the same chat, that's the goal.
If you have other features to offer I'm interested!

You can close the issue.
Good continuation
